######################################################################
# Automatically generated by qmake (3.1) Sat Jul 13 03:58:50 2024
######################################################################

TEMPLATE = app
TARGET = Pac-Man
INCLUDEPATH += .
INCLUDEPATH += sources

QT += widgets

!wasm {
    QT += multimedia
}

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += sources/blinky.h \
           sources/clyde.h \
           sources/dot.h \
           sources/energizer.h \
           sources/entity.h \
           sources/gameboard.h \
           sources/ghost.h \
           sources/icon.h \
           sources/inky.h \
           sources/introscreen.h \
           sources/maze.h \
           sources/pinky.h \
           sources/player.h \
           sources/soundManager.h
SOURCES += sources/blinky.cpp \
           sources/clyde.cpp \
           sources/dot.cpp \
           sources/energizer.cpp \
           sources/entity.cpp \
           sources/gameboard.cpp \
           sources/ghost.cpp \
           sources/icon.cpp \
           sources/inky.cpp \
           sources/introscreen.cpp \
           sources/main.cpp \
           sources/maze.cpp \
           sources/pinky.cpp \
           sources/player.cpp \
           sources/soundManager.cpp

RESOURCES += \
    resources.qrc
